---
- name: install webserver  
  hosts: web
  become: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=present

    - name: start the apache service
      service: name=apache2 state=started  

    - name: copy the file to apache documentroot
      copy: src=index.html dest=/var/www/html



